---
- name: Playbook for Copying files from host to remote and placing them in the Nginx folder.
  hosts: all
  become: true
  remote_user: ubuntu
  vars:
    service_name: nginx

  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ../website/
        dest: /var/www/html
        mode: 0644
      notify:
      - restart nginx

    - name: Remove default index page
      file:
        state: absent
        path: /var/wwww/html/index.nginx-debian.html
    
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
